### ISSUE TITLE
Add SegWit support to BTC

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/airgap-coin-lib#13]

**Comment by JosemyDuarte** [comment]
Looks like this could be closed. I see the option on the app, and also Protocol definition is [here](https://github.com/airgap-it/airgap-coin-lib/blob/3c517e39187c52d95814fb75a24a1f8a040d6bca/packages/bitcoin/src/v0/protocol/BitcoinSegwitProtocol.ts#L10).
