### ISSUE TITLE
No USD price and chart

### ISSUE THREAD

**Issue by skkw** [airgap-it/airgap-coin-lib#14]
For AE tokens in the wallet, we see a balance $0.0, without any chart showing the token price changes.

Seems like the functionality is handled here: https://github.com/airgap-it/airgap-coin-lib/blob/2baa04c18386b0178c4dd3417160f453f1809087/packages/core/src/dependencies/src/cryptocompare-0.5.0/index.js#L30-L36

When fetching the price directly it works:
```
$ curl -s "https://min-api.cryptocompare.com/data/price?fsym=AE&tsyms=USD" | jq '.'
{
  "USD": 0.1917
}
```

It worked fine couple months ago.

**Comment by PrimozO** [comment]
Hi @airgap-gitlab any update on this one? Since it worked flawlessly a few weeks ago it should probably not be too hard to fix it?

**Comment by AndreasGassmann** [comment]
It should work again now.

**Comment by PrimozO** [comment]
Thank you @AndreasGassmann .
