### ISSUE TITLE
TezosKtProtocol.delegateInfo misleading

### ISSUE THREAD

**Issue by dcale** [airgap-it/airgap-coin-lib#5]
naming on two methods is misleading:

TezosKtProtocol.delegateInfo returns DelegationRewardInfo

and 

TezosKtProtocol.isAddressDelegated returns DelegationInfo

The naming would suggest that I receive in the first call  "DelegationInfo" (because I'm not asking form rewards info) and the second call I would expect to receive a boolean.

-> change the naming or change the return.

**Comment by AndreasGassmann** [comment]
This has been changed to be more intuitive.
